format = """
$os\
[ ](fg:#308dff)\
$directory\
$git_branch\
$git_status \
$line_break\
$python\
$golang\
$character"""

[fill]
symbol = " "

[os]
format = '[$symbol](bold white) '   
disabled = false

[os.symbols]
Windows = '󰖳'
Arch = '󰣇'
Ubuntu = ''
Macos = '󰀵'

[directory]
style = ""
read_only = " "
truncate_to_repo = true
format = "[$path]($style)"

[character]
success_symbol = "[❯](#9400FF)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[python]
style = "fg:bold white"
pyenv_version_name = true
detect_extensions = []
format = '[ ]($style)[$virtualenv ]($style)'


[golang]
format = '[Go $version](#00FFFF) '

[git_branch]
symbol = ' '
format = '  [$symbol$branch]($style)'
# truncation_length = 4
truncation_symbol = '…/'
style = 'bold green'

# Shows current git status
[git_status]
format = '([ \( $all_status$ahead_behind\)]($style) )'
style = 'bold green'
conflicted = '[ confliced=${count}](red) '
up_to_date = '[󰘽 up-to-date](green) '
untracked = '[󰋗 untracked=${count}](red) '
ahead = ' ahead=${count}'
diverged = ' ahead=${ahead_count}  behind=${behind_count}'
behind = ' behind=${count}'
stashed = '[ stashed=${count}](green) '
modified = '[󰛿 modified=${count}](yellow) '
staged = '[󰐗 staged=${count}](green) '
renamed = '[󱍸 renamed=${count}](yellow) '
deleted = '[󰍶 deleted=${count}](red) '


